OAUTH_URL = "https://www.amazon.com/ap/oa"
ACCESS_TOKEN_URL = "https://api.amazon.com/auth/o2/token"
PROFILE_URL = "https://api.amazon.com/user/profile"
VENDORS_URL = "https://api.amazonalexa.com/v1/vendors"
SKILLS_URL_PREFIX = "https://api.amazonalexa.com/v1/skills?vendorId="
CLIENT_ID = "amzn1.application-oa2-client.c4c3bb0c0bde4f1f84ca5681a7b8f0a6"
SCOPE = "profile alexa::ask:skills:readwrite alexa::ask:models:readwrite"
CLIENT_SECRET = "1aae01311eee02e0aae19ed3fb68dad91d24de25b6b84805af4b3fc2da76dce8"
REDIRECT_SUFFIX = "users/processlogin"
